Add 1.9.11
makerdao/mcd-changelog pull request #158
Opened 2021-11-26 20:11 UTC by hexonaut

Goerli isn't finished yet, so that should go in a separate PR.

2021-11-26 21:08 UTC, gbalabasquer commented
@hexonaut new Goerli addresses to be added: https://github.com/makerdao/spells-goerli/blob/PE-756/src/Goerli-DssSpell.sol#L55

2021-11-29 13:17 UTC, zdumitru requested changes
@hexonaut Once added Goerli addresses, please also update 'active' links for Goerli.

2021-11-29 14:21 UTC, naszam commented on index.html
>  						<li><a href="/releases/goerli/1.9.10/index.html">Release 1.9.10</a> (Friday, 2021-11-19</li>
missing end parenthesis

2021-11-29 14:29 UTC, gbalabasquer commented on releases/mainnet/1.9.11/index.html
> +						<li>DSS deploy scripts (<a href="https://github.com/makerdao/dss-deploy-scripts/releases/tag/1.9.11" target="_blank">changelog</a>)</li>
I'll get this created soon, so I think is fine to keep it. Otherwise it can be commented and I'll send a new PR to uncomment it.

2021-11-29 15:19 UTC, gbalabasquer approved these changes
LGTM

2021-11-29 16:00 UTC, merged