add goerli-1.10.1
makerdao/mcd-changelog pull request #165
Opened 2022-03-05 00:02 UTC by julienmartinlevrai

2022-03-06 15:55 UTC, hexonaut approved these changes

2022-03-07 12:02 UTC, hexonaut requested changes
Changing from approval. Some changes will be requested soon.

2022-03-10 12:29 UTC, zdumitru approved these changes

2022-03-11 15:24 UTC, julienmartinlevrai commented
@gbalabasquer

2022-03-11 15:32 UTC, julienmartinlevrai commented
closing in favor of https://github.com/makerdao/mcd-changelog/pull/166

2022-03-11 15:32 UTC, closed without merging