Add 1.1.2 addresses for kovan
makerdao/mcd-changelog pull request #86
Opened 2020-09-24 14:28 UTC by gbalabasquer

I've linked the latest to 1.1.2. I'll keep doing that until we get it renamed to `active` or `current`

2020-09-24 16:21 UTC, kmbarry1 submitted a review, later dismissed
LGTM

2020-09-24 16:33 UTC, zdumitru requested changes

2020-09-24 16:33 UTC, zdumitru commented on index.html
> +						<li><a href="/releases/kovan/1.1.1/index.html">Release 1.1.2</a> (Thursday, 24.09.2020)</li>
@gbalabasquer The link says it's 1.1.1

2020-09-24 16:37 UTC, gbalabasquer commented on index.html
> +						<li><a href="/releases/kovan/1.1.1/index.html">Release 1.1.2</a> (Thursday, 24.09.2020)</li>
thanks, fixed

2020-09-24 16:43 UTC, zdumitru approved these changes

2020-09-25 17:04 UTC, gbalabasquer commented
Closing this PR as we should have the mainnet addresses today, so doing both in the same branch.

2020-09-25 17:04 UTC, closed without merging