Add 1.2.0 version
makerdao/mcd-changelog pull request #99
Opened 2020-11-25 19:14 UTC by gbalabasquer

2020-11-25 19:15 UTC, gbalabasquer commented
@brianmcmichael Could you please get the ipfs deployed?
Kovan: https://github.com/makerdao/mcd-changelog/blob/1.2.0/releases/kovan/1.2.0/contracts.json
Mainnet: https://github.com/makerdao/mcd-changelog/blob/1.2.0/releases/mainnet/1.2.0/contracts.json

2020-12-01 18:19 UTC, zdumitru requested changes
See the comment above.

2020-12-01 18:19 UTC, zdumitru commented on releases/mainnet/1.2.0/abi/index.html
> +		<p>Download an <a href="/releases/mainnet/1.1.4/abi/mainnet_abi_1.2.0.zip" target="_blank">archive of all Mainnet 1.2.0 ABIs</a>.<p>
Should be 1.2.0 in both places

2020-12-01 18:34 UTC, gbalabasquer commented on releases/mainnet/1.2.0/abi/index.html
> +		<p>Download an <a href="/releases/mainnet/1.1.4/abi/mainnet_abi_1.2.0.zip" target="_blank">archive of all Mainnet 1.2.0 ABIs</a>.<p>
Fixed

2020-12-01 18:43 UTC, kmbarry1 approved these changes
LGTM

2020-12-01 18:58 UTC, brianmcmichael approved these changes
LGTM

2020-12-02 10:13 UTC, zdumitru approved these changes

2020-12-02 10:13 UTC, merged